EXAMPLE_BIN=netchannel

include ../Makefile.conf

netchannel: Intermediate/netchannel_demo.o
	$(CXX) Intermediate/netchannel_demo.o -o netchannel_demo -lclanCore -lclanApp -lclanNetwork -lclanDisplay
